# Generated by Django 3.2.8 on 2021-10-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(max_length=500)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
