# Generated by Django 3.2.8 on 2021-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('order', models.CharField(default='[]', max_length=500)),
            ],
        ),
    ]
