# Generated by Django 3.2.8 on 2021-10-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
